spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    hostname: localhost
    username: guest
    password: guest
    notification:
      exchange: E_NOTIFICATION
      queue: Q_CAMPAIGN_NOTIFICATION
      routekey: notification
